# Generated by Django 6.0.7 on 2026-09-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_blits_blitsquestion_blits_questions'),
        ('progress', '0002_savedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlitsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='content.blits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blits_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blits natijasi',
                'verbose_name_plural': 'Blits natijalari',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'blits', '-score'], name='progress_bl_user_id_360dd6_idx')],
            },
        ),
    ]
