# Generated by Django 6.0.7 on 2026-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='Faqat PRO uchun'),
        ),
    ]
