# Generated by Django 6.0.7 on 2026-08-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_ticket_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
