# Generated by Django 6.0.7 on 2026-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_question_explanation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
