# Generated by Django 6.0.7 on 2026-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_in_web',
            field=models.BooleanField(default=False, verbose_name='Webda'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Nashr etilgan'),
        ),
    ]
