# Generated by Django 6.0.7 on 2026-09-27 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_publish_existing_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_cry', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blits',
                'verbose_name_plural': 'Blitslar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BlitsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('blits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.blits')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('blits', 'question')},
            },
        ),
        migrations.AddField(
            model_name='blits',
            name='questions',
            field=models.ManyToManyField(related_name='blits_sets', through='content.BlitsQuestion', to='content.question'),
        ),
    ]
