# Generated by Django 6.0.7 on 2026-09-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_blits_blitsquestion_blits_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
