# Generated by Django 6.0.7 on 2026-09-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='F.I.O.')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('password', models.CharField(max_length=10, verbose_name='Parol (ochiq)')),
                ('hujjat', models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=1, verbose_name='Hujjat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='billing.branch', verbose_name='Filial')),
                ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
