# Generated by Django 6.0.7 on 2026-09-27 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0007_blits_blitsquestion_blits_questions'),
        ('progress', '0002_savedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveSmallIntegerField(verbose_name='Rejim (20/50)')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('pass_score', models.PositiveIntegerField()),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='progress.examattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imtihon sessiyasi',
                'verbose_name_plural': 'Imtihon sessiyalari',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.examsession')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', '-started_at'], name='exams_exams_user_id_d81adf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsessionquestion',
            unique_together={('session', 'question')},
        ),
    ]
