# Generated by Django 6.0.7 on 2026-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', "O'quvchi"), ('teacher', "O'qituvchi"), ('admin', 'Shef')], db_index=True, default='student', max_length=10, verbose_name='Rol'),
        ),
    ]
