# Generated by Django 6.0.7 on 2026-09-27 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_devices',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Qurilma limiti'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('mobile', 'Mobil'), ('web', 'Web'), ('desktop', 'Desktop')], db_index=True, default='mobile', max_length=10)),
                ('refresh_jti', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['user', 'platform', 'is_active'], name='accounts_de_user_id_eaf22b_idx')],
            },
        ),
    ]
