# Generated by Django 6.0.7 on 2026-09-27 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_max_devices_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Kod')),
                ('valid_days', models.PositiveSmallIntegerField(verbose_name='Necha kun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_codes', to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Kirish kodi',
                'verbose_name_plural': 'Kirish kodlari',
                'ordering': ('-created_at',),
            },
        ),
    ]
