# Generated by Django 6.0.7 on 2026-09-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accesscode'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='billing.branch', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='user',
            name='hujjat',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], default='-', max_length=1, verbose_name='Hujjat'),
        ),
    ]
