# Generated by Django 6.0.7 on 2026-08-31 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=13)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha (lotin)"), ('kr', 'Ўзбекча (кирилл)'), ('ru', 'Русский')], default='uz', max_length=2)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram hisob',
                'verbose_name_plural': 'Telegram hisoblar',
            },
        ),
    ]
